"""
Skill alias dictionary for the resume matcher.

Source
------
Based on the O*NET(R) 30.2 Database (U.S. Department of Labor,
Employment and Training Administration, National Center for O*NET
Development). Retrieved April 2026 from
https://www.onetcenter.org/database.html

- Technology skills: taken from the "Technology Skills" file, filtered
  to entries marked as Hot Technology or In-Demand.
- General / soft skills: taken from the "Skills" file (all 35 elements).

Cleanup
-------
Some O*NET entries had verbose names that don't match what students
actually write on resumes (e.g. "Amazon Web Services AWS software",
"Hypertext markup language HTML"). We shortened those to the names
people actually use ("AWS", "HTML"). We also added common abbreviations
as aliases (e.g. "JS" -> "JavaScript", "K8s" -> "Kubernetes").

The original O*NET names are kept as additional aliases so the system
still matches when a document happens to use the long form.

O*NET is a trademark of USDOL/ETA. O*NET data is distributed under
a Creative Commons Attribution 4.0 International License.

Structure
---------
SKILL_ALIASES maps a lowercase alias string to a canonical display
name. The skill extractor scans resume text for these aliases and
reports the canonical name if matched.
"""

SKILL_ALIASES = {
    '.net framework': '.NET Framework',
    '3ds max': '3ds Max',
    'accounting software': 'Accounting software',
    'active directory': 'Active Directory',
    'active learning': 'Active Learning',
    'active listening': 'Active Listening',
    'adobe acrobat': 'Adobe Acrobat',
    'adobe after effects': 'Adobe After Effects',
    'adobe analytics': 'Adobe Analytics',
    'adobe creative cloud': 'Adobe Creative Cloud',
    'adobe creative cloud software': 'Adobe Creative Cloud',
    'adobe illustrator': 'Adobe Illustrator',
    'adobe indesign': 'Adobe InDesign',
    'adobe photoshop': 'Adobe Photoshop',
    'adobe photoshop lightroom': 'Adobe Photoshop Lightroom',
    'adobe premiere pro': 'Adobe Premiere Pro',
    'adobe xd': 'Adobe XD',
    'adp workforce now': 'ADP Workforce Now',
    'agile': 'Agile',
    'ahrefs site explorer': 'Ahrefs Site Explorer',
    'ai': 'Artificial Intelligence',
    'ajax': 'AJAX',
    'alteryx software': 'Alteryx software',
    'amadeus crs': 'Amadeus CRS',
    'amazon dynamodb': 'DynamoDB',
    'amazon ec2': 'Amazon EC2',
    'amazon elastic compute cloud ec2': 'Amazon EC2',
    'amazon redshift': 'Amazon Redshift',
    'amazon web services aws cloudformation': 'AWS CloudFormation',
    'amazon web services aws sagemaker': 'AWS SageMaker',
    'amazon web services aws software': 'AWS',
    'android': 'Android',
    'angular': 'Angular',
    'ansible': 'Ansible',
    'ansible software': 'Ansible',
    'ansys simulation software': 'ANSYS simulation software',
    'apache airflow': 'Apache Airflow',
    'apache cassandra': 'Cassandra',
    'apache hadoop': 'Hadoop',
    'apache hive': 'Hive',
    'apache jmeter': 'JMeter',
    'apache kafka': 'Kafka',
    'apache maven': 'Maven',
    'apache spark': 'Spark',
    'apache subversion svn': 'SVN',
    'apache tomcat': 'Tomcat',
    'appium': 'Appium',
    'apple final cut pro': 'Final Cut Pro',
    'apple ios': 'iOS',
    'apple macos': 'macOS',
    'apple safari': 'Safari',
    'applicant tracking software': 'Applicant Tracking Software',
    'arcgis': 'ArcGIS',
    'arcgis survey 123': 'ArcGIS Survey 123',
    "archivists' toolkit": "Archivists' Toolkit",
    'arcpy': 'ArcPy',
    'artificial intelligence': 'Artificial Intelligence',
    'asana': 'Asana',
    'asp': 'ASP',
    'asp.net': 'ASP.NET',
    'atlassian bitbucket': 'Bitbucket',
    'atlassian confluence': 'Confluence',
    'atlassian jira': 'Jira',
    'aurora helioscope': 'Aurora HelioScope',
    'autocad': 'AutoCAD',
    'autocad civil 3d': 'AutoCAD Civil 3D',
    'autodesk 3ds max': '3ds Max',
    'autodesk autocad': 'AutoCAD',
    'autodesk autocad civil 3d': 'AutoCAD Civil 3D',
    'autodesk maya': 'Maya',
    'autodesk navisworks': 'Navisworks',
    'autodesk revit': 'Revit',
    'aws': 'AWS',
    'aws cloudformation': 'AWS CloudFormation',
    'aws ec2': 'Amazon EC2',
    'aws sagemaker': 'AWS SageMaker',
    'azure': 'Azure',
    'azure data factory': 'Azure Data Factory',
    'azure devops': 'Azure DevOps',
    'bash': 'Bash',
    'bentley microstation': 'Bentley MicroStation',
    'bgp': 'BGP',
    'bing ads': 'Bing Ads',
    'bitbucket': 'Bitbucket',
    "blackbaud the raiser's edge": "Blackbaud The Raiser's Edge",
    'bootstrap': 'Bootstrap',
    'border gateway protocol bgp': 'BGP',
    'business software': 'Business Software',
    'business software applications': 'Business Software',
    'c': 'C',
    'c#': 'C#',
    'c++': 'C++',
    'canva': 'Canva',
    'cascading style sheets css': 'CSS',
    'cassandra': 'Cassandra',
    'catia': 'CATIA',
    'chaos enscape': 'Chaos Enscape',
    'chatbot software': 'Chatbot software',
    'chef': 'Chef',
    'ci/cd': 'CI/CD',
    'cicd': 'CI/CD',
    'cinema 4d': 'Cinema 4D',
    'cisco webex': 'Cisco Webex',
    'clinical trial management software': 'Clinical trial management software',
    'cms': 'CMS',
    'complex problem solving': 'Complex Problem Solving',
    'confluence': 'Confluence',
    'constructconnect planswift': 'ConstructConnect PlanSwift',
    'content management systems cms': 'CMS',
    'coordination': 'Coordination',
    'cpp': 'C++',
    'creo parametric': 'Creo Parametric',
    'critical thinking': 'Critical Thinking',
    'crm software': 'CRM Software',
    'csharp': 'C#',
    'css': 'CSS',
    'cubic synchro studio': 'Cubic Synchro Studio',
    'customer relationship management crm software': 'CRM Software',
    'dassault systemes catia': 'CATIA',
    'dassault systemes solidworks': 'SolidWorks',
    'data analysis': 'Data Analysis',
    'data science': 'Data Science',
    'davinci resolve': 'DaVinci Resolve',
    'deep learning': 'Deep Learning',
    'disassembler software': 'Disassembler software',
    'django': 'Django',
    'dl': 'Deep Learning',
    'docker': 'Docker',
    'drupal': 'Drupal',
    'dynamodb': 'DynamoDB',
    'eai software': 'EAI Software',
    'ec2': 'Amazon EC2',
    'eclinicalworks': 'eClinicalWorks',
    'eclinicalworks ehr software': 'eClinicalWorks',
    'eclipse ide': 'Eclipse IDE',
    'elasticsearch': 'Elasticsearch',
    'electronic lab notebook software': 'Electronic lab notebook software',
    'emass': 'eMASS',
    'enterprise application integration eai software': 'EAI Software',
    'epic systems': 'Epic Systems',
    'equipment maintenance': 'Equipment Maintenance',
    'equipment selection': 'Equipment Selection',
    'esri arcgis arcpy': 'ArcPy',
    'esri arcgis software': 'ArcGIS',
    'esri arcgis survey 123': 'ArcGIS Survey 123',
    'etap': 'ETAP',
    'excel': 'Excel',
    'extensible markup language xml': 'XML',
    'facebook': 'Facebook',
    'figma': 'Figma',
    'final cut pro': 'Final Cut Pro',
    'firefox': 'Firefox',
    'firewall software': 'Firewall software',
    'forsk atoll': 'Forsk Atoll',
    'fortran': 'Fortran',
    'g-code': 'G-code',
    'gcp': 'Google Cloud',
    'geographic information system gis software': 'GIS Software',
    'geographic information system gis systems': 'GIS',
    'gis': 'GIS',
    'gis software': 'GIS Software',
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'go': 'Go',
    'golang': 'Go',
    'google': 'Google',
    'google ads': 'Google Ads',
    'google analytics': 'Google Analytics',
    'google android': 'Android',
    'google angular': 'Angular',
    'google cloud': 'Google Cloud',
    'google cloud platform': 'Google Cloud',
    'google docs': 'Google Docs',
    'google meet': 'Google Meet',
    'google sheets': 'Google Sheets',
    'google tag manager': 'Google Tag Manager',
    'google workspace': 'Google Workspace',
    'google workspace software': 'Google Workspace',
    'grafana labs grafana cloud': 'Grafana Labs Grafana Cloud',
    'graphql': 'GraphQL',
    'guidance software encase enterprise': 'Guidance Software EnCase Enterprise',
    'hadoop': 'Hadoop',
    'hec-hms': 'HEC-HMS',
    'hec-ras': 'HEC-RAS',
    'henry schein dentrix': 'Henry Schein Dentrix',
    'hibernate orm': 'Hibernate ORM',
    'hive': 'Hive',
    'html': 'HTML',
    'hubspot software': 'HubSpot software',
    'hypertext markup language html': 'HTML',
    'ibm db2': 'IBM DB2',
    'ibm spss statistics': 'SPSS',
    'ibm terraform': 'Terraform',
    'ibm websphere mq': 'IBM WebSphere MQ',
    'iis': 'IIS',
    'iis manager': 'IIS Manager',
    'informatica software': 'Informatica software',
    'installation': 'Installation',
    'instructing': 'Instructing',
    'intuit quickbooks': 'QuickBooks',
    'intuit turbotax': 'TurboTax',
    'inventory control system software': 'Inventory control system software',
    'inventory management systems': 'Inventory management systems',
    'invision software': 'InVision software',
    'ios': 'iOS',
    'j2ee': 'J2EE',
    'java': 'Java',
    'javascript': 'JavaScript',
    'javascript framework software': 'JavaScript Frameworks',
    'javascript frameworks': 'JavaScript Frameworks',
    'javascript object notation json': 'JSON',
    'jenkins': 'Jenkins',
    'jenkins ci': 'Jenkins',
    'jest': 'Jest',
    'jira': 'Jira',
    'jmeter': 'JMeter',
    'jquery': 'jQuery',
    'js': 'JavaScript',
    'json': 'JSON',
    'judgment and decision making': 'Judgment and Decision Making',
    'junit': 'JUnit',
    'k8s': 'Kubernetes',
    'kafka': 'Kafka',
    'kali linux': 'Kali Linux',
    'kronos workforce timekeeper': 'Kronos Workforce Timekeeper',
    'kubernetes': 'Kubernetes',
    'labview': 'LabVIEW',
    'learning management system lms': 'LMS',
    'learning strategies': 'Learning Strategies',
    'linux': 'Linux',
    'llvm': 'LLVM',
    'lms': 'LMS',
    'low-level virtual machine llvm compilers': 'LLVM',
    'lumion': 'Lumion',
    'machine learning': 'Machine Learning',
    'macos': 'macOS',
    'magellan firmware': 'Magellan Firmware',
    'management of financial resources': 'Management of Financial Resources',
    'management of material resources': 'Management of Material Resources',
    'management of personnel resources': 'Management of Personnel Resources',
    'mapinfo professional': 'MapInfo Professional',
    'marketo marketing automation': 'Marketo Marketing Automation',
    'mastercam computer-aided design and manufacturing software': 'Mastercam computer-aided design and manufacturing software',
    'mathematics': 'Mathematics',
    'mathworks simulink': 'MathWorks Simulink',
    'matlab': 'MATLAB',
    'maven': 'Maven',
    'maxon cinema 4d': 'Cinema 4D',
    'maya': 'Maya',
    'mcneel rhinoceros 3d': 'Rhinoceros 3D',
    'meditech software': 'MEDITECH software',
    'metasploit': 'Metasploit',
    'microsoft .net framework': '.NET Framework',
    'microsoft access': 'Microsoft Access',
    'microsoft active directory': 'Active Directory',
    'microsoft active server pages asp': 'ASP',
    'microsoft asp.net': 'ASP.NET',
    'microsoft azure data factory': 'Azure Data Factory',
    'microsoft azure devops services': 'Azure DevOps',
    'microsoft azure software': 'Azure',
    'microsoft edge': 'Microsoft Edge',
    'microsoft excel': 'Excel',
    'microsoft internet information services (iis)': 'IIS',
    'microsoft internet information services (iis) manager': 'IIS Manager',
    'microsoft office': 'Microsoft Office',
    'microsoft office software': 'Microsoft Office',
    'microsoft outlook': 'Outlook',
    'microsoft power automate': 'Power Automate',
    'microsoft power bi': 'Power BI',
    'microsoft power platform software': 'Power Platform',
    'microsoft powerpoint': 'PowerPoint',
    'microsoft powershell': 'PowerShell',
    'microsoft project': 'Microsoft Project',
    'microsoft sharepoint': 'SharePoint',
    'microsoft sql server': 'SQL Server',
    'microsoft sql server integration services ssis': 'SSIS',
    'microsoft sql server reporting services ssrs': 'SSRS',
    'microsoft team foundation server': 'TFS',
    'microsoft teams': 'Microsoft Teams',
    'microsoft visio': 'Visio',
    'microsoft visual basic': 'Visual Basic',
    'microsoft visual basic for applications vba': 'VBA',
    'microsoft visual studio': 'Visual Studio',
    'microsoft windows': 'Windows',
    'microsoft windows server': 'Windows Server',
    'microsoft word': 'Microsoft Word',
    'mitre att&ck software': 'MITRE ATT&CK software',
    'ml': 'Machine Learning',
    'mongo': 'MongoDB',
    'mongodb': 'MongoDB',
    'monitoring': 'Monitoring',
    'moz search engine optimization seo software': 'SEO Software',
    'mozilla firefox': 'Firefox',
    'ms excel': 'Excel',
    'ms office': 'Microsoft Office',
    'ms powerpoint': 'PowerPoint',
    'ms word': 'Microsoft Word',
    'mysql': 'MySQL',
    'national instruments labview': 'LabVIEW',
    'natural language processing': 'Natural Language Processing',
    'navisworks': 'Navisworks',
    'navisworks jetstream': 'NavisWorks Jetstream',
    'negotiation': 'Negotiation',
    'next.js': 'Next.js',
    'nextjs': 'Next.js',
    'nlp': 'Natural Language Processing',
    'nmap': 'Nmap',
    'node': 'Node.js',
    'node.js': 'Node.js',
    'nodejs': 'Node.js',
    'nosql': 'NoSQL',
    'numpy': 'NumPy',
    'object-oriented programming': 'Object-Oriented Programming',
    'ods': 'ODS',
    'on center on-screen takeoff': 'On Center On-Screen Takeoff',
    'oop': 'Object-Oriented Programming',
    'openroads designer': 'OpenRoads Designer',
    'openshift': 'OpenShift',
    'operating system software': 'Operating system software',
    'operation and control': 'Operation and Control',
    'operational data store ods software': 'ODS',
    'operations analysis': 'Operations Analysis',
    'operations monitoring': 'Operations Monitoring',
    'oracle cloud': 'Oracle Cloud',
    'oracle cloud software': 'Oracle Cloud',
    'oracle database': 'Oracle Database',
    'oracle hris': 'Oracle HRIS',
    'oracle java': 'Java',
    'oracle java 2 platform enterprise edition j2ee': 'J2EE',
    'oracle peoplesoft': 'PeopleSoft',
    'oracle pl/sql': 'PL/SQL',
    'oracle primavera enterprise project portfolio management': 'Oracle Primavera Enterprise Project Portfolio Management',
    'oracle sql developer': 'Oracle SQL Developer',
    'order management software': 'Order management software',
    'orion law management systems orion': 'Orion Law Management Systems Orion',
    'outage management system oms': 'Outage management system OMS',
    'outlook': 'Outlook',
    'pandas': 'pandas',
    'payroll software': 'Payroll software',
    'pci express pcie': 'PCIe',
    'pcie': 'PCIe',
    'peoplesoft': 'PeopleSoft',
    'perforce software': 'Perforce software',
    'perl': 'Perl',
    'persuasion': 'Persuasion',
    'php': 'PHP',
    'pl/sql': 'PL/SQL',
    'pms': 'PMS',
    'portswigger burp suite': 'Portswigger BurP Suite',
    'postgres': 'PostgreSQL',
    'postgresql': 'PostgreSQL',
    'postman': 'Postman',
    'power automate': 'Power Automate',
    'power bi': 'Power BI',
    'power platform': 'Power Platform',
    'powerpoint': 'PowerPoint',
    'powershell': 'PowerShell',
    'procore software': 'Procore software',
    'productivity software': 'Productivity software',
    'programming': 'Programming',
    'project management software': 'Project management software',
    'property management system pms software': 'PMS',
    'ptc creo parametric': 'Creo Parametric',
    'ptv vissim': 'PTV Vissim',
    'puppet': 'Puppet',
    'purchasing software': 'Purchasing software',
    'pvsyst': 'PVsyst',
    'py': 'Python',
    'pyspark': 'PySpark',
    'python': 'Python',
    'pytorch': 'PyTorch',
    'qgis': 'QGIS',
    'quality control analysis': 'Quality Control Analysis',
    'qualtrics insight': 'Qualtrics Insight',
    'qualys cloud platform': 'Qualys Cloud Platform',
    'quickbooks': 'QuickBooks',
    'r': 'R',
    'rdbms': 'RDBMS',
    'react': 'React',
    'react redux': 'Redux',
    'react.js': 'React',
    'reactjs': 'React',
    'reading comprehension': 'Reading Comprehension',
    'red hat enterprise linux': 'RHEL',
    'red hat openshift': 'OpenShift',
    'redcap research electronic data capture': 'REDCap Research Electronic Data Capture',
    'redis': 'Redis',
    'redux': 'Redux',
    'relational database management system software': 'RDBMS',
    'repairing': 'Repairing',
    'reporting software': 'Reporting software',
    'rest': 'RESTful API',
    'rest api': 'RESTful API',
    'restful': 'RESTful API',
    'restful api': 'RESTful API',
    'revit': 'Revit',
    'rhel': 'RHEL',
    'rhinoceros 3d': 'Rhinoceros 3D',
    'rockware arcmap': 'RockWare ArcMap',
    'ruby': 'Ruby',
    'rust': 'Rust',
    'rust programming language': 'Rust',
    'sabre central command': 'Sabre Central Command',
    'safari': 'Safari',
    'salesforce': 'Salesforce',
    'salesforce software': 'Salesforce',
    'sap': 'SAP',
    'sap concur': 'SAP Concur',
    'sap erp': 'SAP ERP',
    'sap software': 'SAP',
    'sas': 'SAS',
    'scala': 'Scala',
    'science': 'Science',
    'scikit-learn': 'scikit-learn',
    'screaming frog seo spider': 'Screaming Frog SEO Spider',
    'scrum': 'Scrum',
    'selenium': 'Selenium',
    'semrush': 'Semrush',
    'seo software': 'SEO Software',
    'service orientation': 'Service Orientation',
    'servicenow': 'ServiceNow',
    'sharepoint': 'SharePoint',
    'shell script': 'Shell Scripting',
    'shell scripting': 'Shell Scripting',
    'shopify software': 'Shopify software',
    'sidefx houdini': 'SideFX Houdini',
    'siemens teamcenter': 'Siemens Teamcenter',
    'single sign-on sso': 'SSO',
    'sis': 'SIS',
    'sketchup': 'SketchUp',
    'sklearn': 'scikit-learn',
    'skm systems analysis power tools': 'SKM Systems Analysis Power Tools',
    'slack': 'Slack',
    'snowflake': 'Snowflake',
    'social perceptiveness': 'Social Perceptiveness',
    'software development tools': 'Software development tools',
    'software libraries': 'Software libraries',
    'solidity': 'Solidity',
    'solidworks': 'SolidWorks',
    'source code editor software': 'Source code editor software',
    'spark': 'Spark',
    'sparta systems trackwise': 'Sparta Systems TrackWise',
    'speaking': 'Speaking',
    'splunk enterprise': 'Splunk Enterprise',
    'spring boot': 'Spring Boot',
    'spring framework': 'Spring Framework',
    'springshare libguides': 'Springshare LibGuides',
    'spss': 'SPSS',
    'sql': 'SQL',
    'sql server': 'SQL Server',
    'ssis': 'SSIS',
    'sso': 'SSO',
    'ssrs': 'SSRS',
    'statacorp stata': 'StataCorp Stata',
    'statistical software': 'Statistical software',
    'structured query language sql': 'SQL',
    'student information systems sis software': 'SIS',
    'svn': 'SVN',
    'swift': 'Swift',
    'systems analysis': 'Systems Analysis',
    'systems evaluation': 'Systems Evaluation',
    'systemverilog': 'SystemVerilog',
    'tableau': 'Tableau',
    'tax compliance property tax management software': 'Tax compliance property tax management software',
    'tax software': 'Tax software',
    'tcl': 'Tcl',
    'tdd': 'Test-Driven Development',
    'technology design': 'Technology Design',
    'techsmith camtasia': 'TechSmith Camtasia',
    'tenable nessus': 'Tenable Nessus',
    'tensorflow': 'TensorFlow',
    'teradata database': 'Teradata Database',
    'terraform': 'Terraform',
    'test-driven development': 'Test-Driven Development',
    'testng': 'TestNG',
    'tf': 'TensorFlow',
    'tfs': 'TFS',
    'the mathworks matlab': 'MATLAB',
    'thomson reuters westlaw': 'Thomson Reuters Westlaw',
    'tiktok': 'TikTok',
    'time management': 'Time Management',
    'tms': 'TMS',
    'tomcat': 'Tomcat',
    'tool command language tcl': 'Tcl',
    'transact-sql': 'Transact-SQL',
    'transportation management system tms software': 'TMS',
    'trimble sketchup pro': 'SketchUp',
    'troubleshooting': 'Troubleshooting',
    'ts': 'TypeScript',
    'turbotax': 'TurboTax',
    'typescript': 'TypeScript',
    'unity': 'Unity',
    'unity technologies unity': 'Unity',
    'unix': 'Unix',
    'unix shell': 'Unix Shell',
    'unreal engine': 'Unreal Engine',
    'unreal technology unreal engine': 'Unreal Engine',
    'vba': 'VBA',
    'verilog': 'Verilog',
    'version control': 'Version Control',
    'version control software': 'Version Control',
    'very high speed integrated circuit vhsic hardware description language vhdl simulation software': 'VHDL',
    'vhdl': 'VHDL',
    'video editing software': 'Video editing software',
    'visio': 'Visio',
    'visual basic': 'Visual Basic',
    'visual studio': 'Visual Studio',
    'vs code': 'VS Code',
    'vscode': 'VS Code',
    'vue': 'Vue.js',
    'vue.js': 'Vue.js',
    'vuejs': 'Vue.js',
    'warehouse management system wms': 'WMS',
    'web application framework software': 'Web Application Frameworks',
    'web application frameworks': 'Web Application Frameworks',
    'web application software': 'Web application software',
    'web browser software': 'Web browser software',
    'web framework software': 'Web Frameworks',
    'web frameworks': 'Web Frameworks',
    'web server software': 'Web server software',
    'windows': 'Windows',
    'windows server': 'Windows Server',
    'wms': 'WMS',
    'wordpress': 'WordPress',
    'workday software': 'Workday software',
    'writing': 'Writing',
    'xactware xactimate': 'Xactware Xactimate',
    'xml': 'XML',
    'yardi software': 'Yardi software',
    'zemax': 'Zemax',
    'zoom': 'Zoom',
}
